<template><h1 id="aspect-ratio" tabindex="-1"><a class="header-anchor" href="#aspect-ratio" aria-hidden="true">#</a> Aspect Ratio</h1>
<p><code>&lt;Aspect&gt;</code> component is a wrapper of <code>Bootstrap 5</code>'s <code>ratio</code> helper. It uses <code>ratio</code> helper classes under the hood.
Default value of <code>ratio</code> is <code>16x9</code>. Supported values of <code>ratio</code> prop are:</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">type</span> <span class="token class-name">ratio</span> <span class="token operator">=</span> <span class="token string">'1x1'</span> <span class="token operator">|</span> <span class="token string">'4x3'</span> <span class="token operator">|</span> <span class="token string">'16x9'</span> <span class="token operator">|</span> <span class="token string">'21x9'</span> <span class="token operator">|</span> <span class="token builtin">number</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>Select</span> <span class="token attr-name">v-model</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>ratio<span class="token punctuation">"</span></span> <span class="token attr-name">:options</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>[<span class="token punctuation">'</span>16x9<span class="token punctuation">'</span>,<span class="token punctuation">'</span>21x9<span class="token punctuation">'</span>,<span class="token punctuation">'</span>4x3<span class="token punctuation">'</span>,<span class="token punctuation">'</span>1x1<span class="token punctuation">'</span>,50,100]<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>Select</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>Aspect</span> <span class="token attr-name">:ratio</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>ratio<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>iframe</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://player.vimeo.com/video/678344029?h=0458dff732<span class="token punctuation">"</span></span>
            <span class="token attr-name">allow</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>autoplay; fullscreen; picture-in-picture<span class="token punctuation">"</span></span>
            <span class="token attr-name">allowfullscreen</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>iframe</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>Aspect</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><WSelect v-model="ratio" :options="['16x9','21x9','4x3','1x1',50,100]"></WSelect>
<WAspect :ratio="ratio">
<iframe src="https://www.youtube.com/embed/z3grFwJwrD0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</WAspect>
</template>

<script setup>
import {ref} from "vue"; 

const ratio=ref('16x9');
</script>