export default [
    '/getting-started/',
    '/accordion/',
    '/alerts/',
    '/badges/',
    '/breadcrumbs/',
    '/buttons/',
    '/buttons/groups/',
    '/buttons/toolbars/',
    '/carousel/',
    '/collapse/',
    '/calendar/',
    '/cards/',
    '/dropdowns/',
    {
        text: 'Form',
        link: '/form/',
        collapsible: true,
        children: [
            "/form/checkbox",
            "/form/input",
            "/form/radio/",
            "/form/rating/",
            "/form/select/",
            "/form/group/",
            "/form/spinbutton/",
            "/form/tags/",
        ].sort()
    },
    '/list-group/',
    '/icons/',
]