<template><h1 id="spin-button" tabindex="-1"><a class="header-anchor" href="#spin-button" aria-hidden="true">#</a> Spin Button</h1>
<p>Spin buttons are a <code>wovoui</code>'s custom numerical range form control. Spin buttons allow for incrementing or decrementing a
numerical value within a range of a minimum and maximum number, with optional step value.</p>
<h2 id="overview" tabindex="-1"><a class="header-anchor" href="#overview" aria-hidden="true">#</a> Overview</h2>
<p>The component <code>&lt;SpinButton&gt;</code> is WAI-ARIA compliant, allowing for keyboard control, and supports both horizontal (
default) and vertical layout.</p>
<WSpinButton></WSpinButton>
<div class="language-vue ext-vue line-numbers-mode"><pre v-pre class="language-vue"><code>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>SpinButton</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>SpinButton</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h2 id="v-model-value" tabindex="-1"><a class="header-anchor" href="#v-model-value" aria-hidden="true">#</a> <code>v-model</code> value</h2>
<p>The <code>v-model</code> always returns the value as a number. The <code>v-model</code> can be <code>null</code> if no <code>initial</code> value is set.</p>
<h2 id="min-max-and-step" tabindex="-1"><a class="header-anchor" href="#min-max-and-step" aria-hidden="true">#</a> <code>min</code>, <code>max</code>, and <code>step</code></h2>
<p>Spinbuttons have a default range from 1 to 100, which can be changed by setting the <code>min</code> and <code>max</code> props. The
default <code>step</code>
increment is 1, and can be changed via the <code>step</code> prop (decimal values allowed).</p>
<p>When <code>step</code> is set, the value will always be a multiple of the step size plus the minimum value.</p>
<WSpinButton :step="0.25"></WSpinButton>
<div class="language-vue ext-vue line-numbers-mode"><pre v-pre class="language-vue"><code>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>SpinButton</span> <span class="token attr-name">:step</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>0.25<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>SpinButton</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h2 id="size" tabindex="-1"><a class="header-anchor" href="#size" aria-hidden="true">#</a> Size</h2>
<p>As with other form controls, <code>&lt;SpinButton&gt;</code> supports <code>small</code> and <code>large</code> sizing via setting the <code>size</code> prop to either
<code>sm</code> or <code>lg</code>, respectively.</p>
<div>
    <label for="sb-small">Spin button - Small size</label>
    <WSpinButton id="sb-small" size="sm" placeholder="--" class="mb-2"></WSpinButton>
    <label for="sb-default">Spin button - Default size</label>
    <WSpinButton id="sb-default" placeholder="--" class="mb-2"></WSpinButton>
    <label for="sb-large">Spin button - Large size</label>
    <WSpinButton id="sb-large" size="lg" placeholder="--" class="mb-2"></WSpinButton>
</div>
<div class="language-vue ext-vue line-numbers-mode"><pre v-pre class="language-vue"><code>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>label</span> <span class="token attr-name">for</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>sb-small<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>Spin button - Small size<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>label</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>SpinButton</span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>sb-small<span class="token punctuation">"</span></span> <span class="token attr-name">size</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>sm<span class="token punctuation">"</span></span> <span class="token attr-name">placeholder</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>--<span class="token punctuation">"</span></span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>mb-2<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>SpinButton</span><span class="token punctuation">></span></span>

<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>label</span> <span class="token attr-name">for</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>sb-default<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>Spin button - Default size<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>label</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>SpinButton</span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>sb-default<span class="token punctuation">"</span></span> <span class="token attr-name">placeholder</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>--<span class="token punctuation">"</span></span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>mb-2<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>SpinButton</span><span class="token punctuation">></span></span>

<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>label</span> <span class="token attr-name">for</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>sb-large<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>Spin button - Large size<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>label</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>SpinButton</span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>sb-large<span class="token punctuation">"</span></span> <span class="token attr-name">size</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>lg<span class="token punctuation">"</span></span> <span class="token attr-name">placeholder</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>--<span class="token punctuation">"</span></span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>mb-2<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>SpinButton</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h2 id="inline" tabindex="-1"><a class="header-anchor" href="#inline" aria-hidden="true">#</a> Inline</h2>
<div>
<label for="sb-inline">Inline spin button</label>
<WSpinButton id="sb-inline" inline></WSpinButton>
</div></template>
