<template><h1 id="spinner" tabindex="-1"><a class="header-anchor" href="#spinner" aria-hidden="true">#</a> Spinner</h1>
<h2 id="about" tabindex="-1"><a class="header-anchor" href="#about" aria-hidden="true">#</a> About</h2>
<p>Bootstrap “spinners” can be used to show the loading state in your projects. They’re built only with HTML and CSS,
meaning you don’t need any JavaScript to create them. You will, however, need some custom JavaScript to toggle their
visibility. Their appearance, alignment, and sizing can be easily customized with our amazing utility classes.</p>
<h2 id="border-spinner" tabindex="-1"><a class="header-anchor" href="#border-spinner" aria-hidden="true">#</a> Border spinner</h2>
<p>Use the border spinners for a lightweight loading indicator.</p>
<WSpinner></WSpinner>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>Spinner</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>Spinner</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h2 id="colors" tabindex="-1"><a class="header-anchor" href="#colors" aria-hidden="true">#</a> Colors</h2>
<WSpinner class="m-1" :variant="v" v-for="v in ['primary','secondary','success','danger','warning','info','light','dark']">
</WSpinner>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>Spinner</span> <span class="token attr-name">:variant</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>v<span class="token punctuation">"</span></span> <span class="token attr-name">v-for</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>v in [<span class="token punctuation">'</span>primary<span class="token punctuation">'</span>,<span class="token punctuation">'</span>secondary<span class="token punctuation">'</span>,<span class="token punctuation">'</span>success<span class="token punctuation">'</span>,<span class="token punctuation">'</span>danger<span class="token punctuation">'</span>,<span class="token punctuation">'</span>warning<span class="token punctuation">'</span>,<span class="token punctuation">'</span>info<span class="token punctuation">'</span>,<span class="token punctuation">'</span>light<span class="token punctuation">'</span>,<span class="token punctuation">'</span>dark<span class="token punctuation">'</span>]<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>Spinner</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h2 id="growing-spinner" tabindex="-1"><a class="header-anchor" href="#growing-spinner" aria-hidden="true">#</a> Growing spinner</h2>
<WSpinner grow></WSpinner>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>Spinner</span> <span class="token attr-name">grow</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>Spinner</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h2 id="grow-spinner-colors" tabindex="-1"><a class="header-anchor" href="#grow-spinner-colors" aria-hidden="true">#</a> Grow Spinner Colors</h2>
<WSpinner grow class="m-1" :variant="v" v-for="v in ['primary','secondary','success','danger','warning','info','light','dark']">
</WSpinner>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>Spinner</span> <span class="token attr-name">grow</span> <span class="token attr-name">:variant</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>v<span class="token punctuation">"</span></span> <span class="token attr-name">v-for</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>v in [<span class="token punctuation">'</span>primary<span class="token punctuation">'</span>,<span class="token punctuation">'</span>secondary<span class="token punctuation">'</span>,<span class="token punctuation">'</span>success<span class="token punctuation">'</span>,<span class="token punctuation">'</span>danger<span class="token punctuation">'</span>,<span class="token punctuation">'</span>warning<span class="token punctuation">'</span>,<span class="token punctuation">'</span>info<span class="token punctuation">'</span>,<span class="token punctuation">'</span>light<span class="token punctuation">'</span>,<span class="token punctuation">'</span>dark<span class="token punctuation">'</span>]<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>Spinner</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h2 id="size" tabindex="-1"><a class="header-anchor" href="#size" aria-hidden="true">#</a> Size</h2>
<WSpinner class="me-2" size="sm"/>
<WSpinner grow size="sm"/>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>Spinner</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>me-2<span class="token punctuation">"</span></span> <span class="token attr-name">size</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>sm<span class="token punctuation">"</span></span><span class="token punctuation">/></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>Spinner</span> <span class="token attr-name">grow</span> <span class="token attr-name">size</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>sm<span class="token punctuation">"</span></span><span class="token punctuation">/></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div></template>
